### ISSUE TITLE
[ BUG ] Missed Gear

### ISSUE THREAD

**Issue by NotTheRealGojo** [BrokenGameNoob/BrokenTC2#9]
Hi, most of the time when I try to change gear it doesn't work. So I can't use it ... 
Is there a solution ? 
Thanks

**Comment by BrokenGameNoob** [comment]
This might come from the "Gear key press delay" begin too short.
It corresponds to the time the key is simulated to be holded down by the software.
If you're experimenting low framerate or lags, a too small delay may lead to some issues.

Try increasing this delay until it works properly.
Keep in mind that it is better if the value remain as small as possible.

20 ms is the default value as it is what I consider being the best compromise between performance and stability on **high end pc**
